Add conda installation information in the README
robotology/bayes-filters-lib pull request #103
Opened 2023-10-27 12:12 UTC by GiulioRomualdi

Hi @xEnVrE and @claudiofantacci, thanks to @traversaro the library is available in conda-forge https://anaconda.org/conda-forge/libbayes-filters-lib I opened this PR to add the information in the readme

2023-10-30 20:37 UTC, xEnVrE requested changes
Thanks @GiulioRomualdi.

Two very small requests from my side.

2023-10-30 20:37 UTC, xEnVrE commented on README.md
> +# Building from sources
Should not we add within this subsection also the part devoted to run tests (as that is only available only after compiling if I am not wrong)?

Thank you

2023-10-30 20:37 UTC, xEnVrE commented on README.md
> +- [Installing with conda](#installing-with-conda)
I think we could add a small icon here to adhere with the style of the `README.md`.

Thank you

2023-11-02 17:29 UTC, GiulioRomualdi commented
Hi @xEnVrE I updated the README

2023-11-02 18:02 UTC, xEnVrE approved these changes
LGTM

2023-11-02 18:03 UTC, merged